display_information:
  name: DevSecOps CI Alerts
  description: GitHub Actions notifications for CI/CD pipeline
  background_color: "#2d333b"

features:
  bot_user:
    display_name: CI Bot
    always_online: false

oauth_config:
  scopes:
    bot:
      - incoming-webhook

settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
