Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.hostname = "kali-pentest"
  
  # Network configuration
  config.vm.network "private_network", type: "dhcp"
  
  # VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.name = "kali-pentest"
    vb.memory = "4096"
    vb.cpus = 2
    vb.gui = false
    
    # Enable synced folder for VirtualBox
    config.vm.synced_folder ".", "/vagrant"
  end
  
  # Libvirt provider
  config.vm.provider "libvirt" do |lv|
    lv.memory = 4096
    lv.cpus = 2
    lv.driver = "kvm"
    
    # Disable synced folder for Libvirt (requires NFS or rsync)
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end
  
  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl jq nmap nikto sqlmap
    
    # Install just
    curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
    
    echo "Kali pentest environment ready!"
    echo "Run: vagrant ssh"
  SHELL
end

